import type { ParsedResource } from '../utils/schema-parser'

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

export function generateCollection(resource: ParsedResource): string {
  const { config, resourceVarName } = resource
  const { name, pluralName, syncMode = 'eager' } = config
  const typeName = capitalize(name)

  return `// 🔄 GENERATED by codegen - modifications may be overwritten

import { createCollection } from '@tanstack/db'
import { queryCollectionOptions } from '@tanstack/db/query-collection'
import { ${resourceVarName}, type ${typeName} } from '@/schemas/${name}.schema'
import { apiClient } from '@/api/client'

const { config, schema } = ${resourceVarName}

export const ${pluralName}Collection = createCollection<${typeName}>(
  queryCollectionOptions({
    queryKey: [config.pluralName],
    schema,
    getId: (item) => item.id,
    syncMode: '${syncMode}',

    queryFn: async (ctx) => {
      const params = ctx.meta?.loadSubsetOptions
      const response = await apiClient.get<${typeName}[]>(
        \`/api/\${config.pluralName}\`,
        { params }
      )
      return response.data
    },

    onInsert: async ({ transaction }) => {
      const { modified } = transaction.mutations[0]
      await apiClient.post(\`/api/\${config.pluralName}\`, modified)
    },

    onUpdate: async ({ transaction }) => {
      const { original, modified } = transaction.mutations[0]
      await apiClient.patch(
        \`/api/\${config.pluralName}/\${original.id}\`,
        modified
      )
    },

    onDelete: async ({ transaction }) => {
      const { original } = transaction.mutations[0]
      await apiClient.delete(\`/api/\${config.pluralName}/\${original.id}\`)
    },
  })
)

export type { ${typeName} }
`
}
