import type { ParsedResource } from '../utils/schema-parser'

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

export function generateCollection(resource: ParsedResource): string {
  const { config, resourceVarName } = resource
  const { name, pluralName } = config
  const typeName = capitalize(name)

  return `// 🔄 GENERATED by codegen - modifications may be overwritten

import { createCollection, localOnlyCollectionOptions } from '@tanstack/db'
import { ${resourceVarName}, type ${typeName} } from '@/schemas/${name}.schema'

const { schema } = ${resourceVarName}

/**
 * ${typeName} collection - uses local-only mode by default.
 * To connect to an API, replace localOnlyCollectionOptions with a custom sync config.
 * See: https://tanstack.com/db/latest/docs/framework/react/guides/sync
 */
export const ${pluralName}Collection = createCollection<typeof schema, string>({
  ...localOnlyCollectionOptions({
    schema,
    getKey: (item) => item.id,
  }),
  id: '${pluralName}',
})

export type { ${typeName} }
`
}
