import type { ParsedResource, ParsedField } from '../utils/schema-parser'

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

export function generateColumns(resource: ParsedResource): string {
  const { config, fields } = resource
  const { name, table } = config
  const typeName = capitalize(name)

  // Get columns to display
  const columnNames = table?.columns ?? fields.map((f) => f.name)
  const visibleFields = columnNames
    .map((colName) => fields.find((f) => f.name === colName))
    .filter((f): f is ParsedField => !!f && !f.meta.hidden)

  // Get filterable fields for faceted filter support
  const filterableFields = table?.filterableFields ?? []

  // Check if any column has a relation
  const hasRelations = visibleFields.some((f) => f.meta.relation)
  
  // Check if we need Badge for status columns
  const hasStatusColumn = visibleFields.some((f) => 
    f.name === 'status' || f.meta.inputType === 'select' || filterableFields.includes(f.name)
  )

  return `// 🔄 GENERATED by codegen

import { ColumnDef } from '@tanstack/react-table'
import { Link } from '@tanstack/react-router'
import { IconDotsVertical, IconPencil } from '@tabler/icons-react'
import { Button } from '@/components/ui/button'
${hasStatusColumn ? "import { Badge } from '@/components/ui/badge'" : ''}
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
${hasRelations ? "import { RelationCell } from '@/components/tables/_column-helpers'" : ''}
import type { ${typeName} } from '@/schemas/${name}.schema'

export const ${name}Columns: ColumnDef<${typeName}>[] = [
${visibleFields.map((f) => generateColumnDef(f, name, filterableFields)).join(',\n')},
  // Actions column
  {
    id: 'actions',
    cell: ({ row }) => {
      const item = row.original
      return (
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="ghost" className="h-8 w-8 p-0">
              <span className="sr-only">Open menu</span>
              <IconDotsVertical className="h-4 w-4" />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuItem asChild>
              <Link to="/${config.pluralName}/$id/edit" params={{ id: item.id }}>
                <IconPencil className="mr-2 h-4 w-4" />
                Edit
              </Link>
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      )
    },
  },
]
`
}

function generateColumnDef(field: ParsedField, resourceName: string, filterableFields: string[]): string {
  const { name, meta } = field
  const header = meta.label ?? capitalize(name.replace(/_/g, ' '))
  const isFilterable = filterableFields.includes(name)

  // Filter function for faceted filtering
  const filterFn = isFilterable ? `
    filterFn: (row, id, value) => {
      return value.includes(row.getValue(id))
    },` : ''

  // Relation column
  if (meta.relation) {
    return `  {
    accessorKey: '${name}',
    header: '${header}',${filterFn}
    cell: ({ row }) => (
      <RelationCell
        resourceName="${meta.relation!.resource}"
        id={row.original.${name}}
        labelField="${meta.relation!.labelField}"
      />
    ),
  }`
  }

  // Status/Select column - show as badge
  if (name === 'status' || (meta.inputType === 'select' && isFilterable)) {
    return `  {
    accessorKey: '${name}',
    header: '${header}',${filterFn}
    cell: ({ row }) => {
      const value = row.getValue('${name}') as string
      return (
        <Badge variant="outline" className="capitalize">
          {value?.replace(/_/g, ' ') ?? '-'}
        </Badge>
      )
    },
  }`
  }

  // Currency column
  if (meta.inputType === 'currency') {
    return `  {
    accessorKey: '${name}',
    header: '${header}',${filterFn}
    cell: ({ row }) => {
      const amount = parseFloat(row.getValue('${name}') ?? '0')
      const formatted = new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: 'USD',
      }).format(amount)
      return <div className="font-medium">{formatted}</div>
    },
  }`
  }

  // Date column
  if (meta.inputType === 'date' || meta.inputType === 'datetime') {
    return `  {
    accessorKey: '${name}',
    header: '${header}',${filterFn}
    cell: ({ row }) => {
      const val = row.getValue('${name}') as string
      if (!val) return <div>-</div>
      const date = new Date(val)
      return <div>{date.toLocaleDateString()}</div>
    },
  }`
  }

  // Default column
  return `  {
    accessorKey: '${name}',
    header: '${header}',${filterFn}
  }`
}
