import type { ParsedResource, ParsedField } from '../utils/schema-parser'

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

export function generateForm(resource: ParsedResource): string {
  const { config, fields, resourceVarName } = resource
  const { name } = config
  const typeName = capitalize(name)

  // Filter out hidden and system fields
  const formFields = fields.filter(
    (f) => !f.meta.hidden && !['id', 'created_at', 'updated_at'].includes(f.name)
  )

  // Check if any field has a relation (needs RelationCombobox import)
  const hasRelations = formFields.some((f) => f.meta.relation)

  // Generate form sections or flat list
  const sections = config.form?.sections

  return `// 🔄 GENERATED by codegen

import { useForm } from '@tanstack/react-form'
import { ${resourceVarName} } from '@/schemas/${name}.schema'
import { FormField } from '@/components/forms/_form-field'
${hasRelations ? "import { RelationCombobox } from '@/components/forms/_relation-combobox'" : ''}
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Trash2 } from 'lucide-react'

type ${typeName}FormProps = {
  defaultValues?: Partial<typeof ${resourceVarName}.type>
  onSubmit: (data: typeof ${resourceVarName}.createSchema._type) => Promise<void>
  onDelete?: () => Promise<void>
}

export function ${typeName}Form({ defaultValues, onSubmit, onDelete }: ${typeName}FormProps) {
  const form = useForm({
    defaultValues: {
${formFields.map((f) => `      ${f.name}: defaultValues?.${f.name} ?? ${getDefaultValue(f)},`).join('\n')}
    },
    onSubmit: async ({ value }) => {
      await onSubmit(value as typeof ${resourceVarName}.createSchema._type)
    },
  })

  return (
    <form
      onSubmit={(e) => {
        e.preventDefault()
        e.stopPropagation()
        form.handleSubmit()
      }}
      className="space-y-6"
    >
${sections ? generateSections(sections, formFields) : generateFlatFields(formFields)}

      {/* Actions */}
      <div className="flex justify-between">
        {onDelete && (
          <Button type="button" variant="destructive" onClick={onDelete}>
            <Trash2 className="mr-2 h-4 w-4" />
            Delete
          </Button>
        )}
        <div className="flex gap-4 ml-auto">
          <Button type="button" variant="outline" onClick={() => window.history.back()}>
            Cancel
          </Button>
          <form.Subscribe
            selector={(state) => [state.canSubmit, state.isSubmitting]}
          >
            {([canSubmit, isSubmitting]) => (
              <Button type="submit" disabled={!canSubmit || isSubmitting}>
                {isSubmitting ? 'Saving...' : 'Save'}
              </Button>
            )}
          </form.Subscribe>
        </div>
      </div>
    </form>
  )
}
`
}

function generateSections(
  sections: { title: string; description?: string; fields: string[] }[],
  formFields: ParsedField[]
): string {
  return sections
    .map(
      (section) => `
      <Card>
        <CardHeader>
          <CardTitle>${section.title}</CardTitle>
          ${section.description ? `<p className="text-sm text-muted-foreground">${section.description}</p>` : ''}
        </CardHeader>
        <CardContent className="space-y-4">
${section.fields
  .map((fieldName) => {
    const field = formFields.find((f) => f.name === fieldName)
    if (!field) return ''
    return generateFieldJSX(field)
  })
  .filter(Boolean)
  .join('\n')}
        </CardContent>
      </Card>`
    )
    .join('\n')
}

function generateFlatFields(formFields: ParsedField[]): string {
  return `
      <Card>
        <CardContent className="space-y-4 pt-6">
${formFields.map(generateFieldJSX).join('\n')}
        </CardContent>
      </Card>`
}

function generateFieldJSX(field: ParsedField): string {
  const { name, meta, isOptional } = field
  const label = meta.label ?? capitalize(name.replace(/_/g, ' '))
  const inputType = meta.inputType ?? 'text'

  // Relation field
  if (meta.relation) {
    return `
          <form.Field name="${name}">
            {(fieldApi) => (
              <div className="space-y-2">
                <label className="text-sm font-medium">${label}${!isOptional ? ' *' : ''}</label>
                <RelationCombobox
                  resourceName="${meta.relation.resource}"
                  labelField="${meta.relation.labelField}"
                  searchFields={${JSON.stringify(meta.relation.searchFields ?? [meta.relation.labelField])}}
                  value={fieldApi.state.value}
                  onChange={(v) => fieldApi.handleChange(v ?? '')}
                  placeholder="Select ${meta.relation.resource}..."
                />
                {fieldApi.state.meta.errors?.[0] && (
                  <p className="text-sm text-destructive">{fieldApi.state.meta.errors[0]}</p>
                )}
              </div>
            )}
          </form.Field>`
  }

  // Regular field
  return `
          <form.Field name="${name}">
            {(fieldApi) => (
              <FormField
                label="${label}"
                inputType="${inputType}"
                value={fieldApi.state.value}
                onChange={(v) => fieldApi.handleChange(v as typeof fieldApi.state.value)}
                onBlur={fieldApi.handleBlur}
                error={fieldApi.state.meta.errors?.[0]}
                ${meta.placeholder ? `placeholder="${meta.placeholder}"` : ''}
                ${meta.description ? `description="${meta.description}"` : ''}
                ${meta.readOnly ? 'readOnly' : ''}
                ${!isOptional ? 'required' : ''}
              />
            )}
          </form.Field>`
}

function getDefaultValue(field: ParsedField): string {
  const { zodType, isOptional } = field

  if (isOptional) return 'undefined'

  switch (zodType) {
    case 'string':
      return "''"
    case 'number':
      return '0'
    case 'boolean':
      return 'false'
    case 'date':
    case 'coerce':
      return 'new Date()'
    case 'enum':
      return "''"
    default:
      return "''"
  }
}
