import type { ParsedResource } from '../utils/schema-parser'

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

export function generateRouteNew(resource: ParsedResource): string {
  const { config } = resource
  const { name, pluralName } = config
  const typeName = capitalize(name)
  const formName = `${typeName}Form`

  return `// 🔄 GENERATED by codegen

import { createFileRoute, useNavigate } from '@tanstack/react-router'
import { ${pluralName}Collection, type ${typeName} } from '@/collections'
import { ${formName} } from '@/components/forms/${name}-form'
import { PageHeader } from '@/components/shared/page-header'
import { toast } from 'sonner'

export const Route = createFileRoute('/_app/${pluralName}/new')({
  component: ${typeName}NewPage,
})

function ${typeName}NewPage() {
  const navigate = useNavigate()

  const handleSubmit = async (data: Omit<${typeName}, 'id' | 'created_at' | 'updated_at'>) => {
    try {
      ${pluralName}Collection.insert({
        ...data,
        id: crypto.randomUUID(),
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      } as ${typeName})
      toast.success('${typeName} created successfully')
      navigate({ to: '/${pluralName}' })
    } catch (error) {
      toast.error('Failed to create ${name}')
      console.error(error)
    }
  }

  return (
    <div className="flex flex-col gap-6">
      <PageHeader
        title="New ${typeName}"
        description="Create a new ${name}"
        backLink="/${pluralName}"
      />

      <div className="max-w-2xl">
        <${formName} onSubmit={handleSubmit} />
      </div>
    </div>
  )
}
`
}
