import type { ParsedResource } from '../utils/schema-parser'

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

export function generateRouteEdit(resource: ParsedResource): string {
  const { config } = resource
  const { name, pluralName, dataSource } = config
  const typeName = capitalize(name)
  const formName = `${typeName}Form`
  const paramName = `${name}Id`
  const apiPath = config.apiBasePath ?? `/${pluralName}`

  // Generate parquet-backed route (mutations via REST API)
  if (dataSource === 'parquet') {
    return generateParquetRouteEdit({ name, pluralName, typeName, formName, paramName, apiPath })
  }

  // Default: JSON/TanStack DB route
  return generateJsonRouteEdit({ name, pluralName, typeName, formName, paramName })
}

type RouteEditParams = {
  name: string
  pluralName: string
  typeName: string
  formName: string
  paramName: string
  apiPath?: string
}

function generateJsonRouteEdit(params: RouteEditParams): string {
  const { name, pluralName, typeName, formName, paramName } = params

  return `// 🔄 GENERATED by codegen

import { createFileRoute, useNavigate } from '@tanstack/react-router'
import { useLiveQuery } from '@tanstack/react-db'
import { ${pluralName}Collection, type ${typeName} } from '@/collections'
import { ${formName} } from '@/components/forms/${name}-form'
import { PageHeader } from '@/components/shared/page-header'
import { toast } from 'sonner'

export const Route = createFileRoute('/_app/${pluralName}/$${paramName}')({
  component: ${typeName}EditPage,
})

function ${typeName}EditPage() {
  const navigate = useNavigate()
  const { ${paramName} } = Route.useParams()

  // Load the item
  const { data } = useLiveQuery((q) =>
    q
      .from({ item: ${pluralName}Collection })
      .where(({ item }) => item.id === ${paramName})
  )

  const item = data?.[0]

  const handleSubmit = async (formData: Partial<${typeName}>) => {
    try {
      ${pluralName}Collection.update(${paramName}, {
        ...formData,
        updated_at: new Date().toISOString(),
      })
      toast.success('${typeName} updated successfully')
      navigate({ to: '/${pluralName}' })
    } catch (error) {
      toast.error('Failed to update ${name}')
      console.error(error)
    }
  }

  const handleDelete = async () => {
    if (!confirm('Are you sure you want to delete this ${name}?')) return

    try {
      ${pluralName}Collection.delete(${paramName})
      toast.success('${typeName} deleted')
      navigate({ to: '/${pluralName}' })
    } catch (error) {
      toast.error('Failed to delete ${name}')
      console.error(error)
    }
  }

  if (!item) {
    return (
      <div className="flex items-center justify-center p-8">
        <p className="text-muted-foreground">Loading...</p>
      </div>
    )
  }

  return (
    <div className="flex flex-col gap-6">
      <PageHeader
        title="Edit ${typeName}"
        description="Update ${name} details"
        backLink="/${pluralName}"
      />

      <div className="max-w-2xl">
        <${formName}
          defaultValues={item}
          onSubmit={handleSubmit}
          onDelete={handleDelete}
        />
      </div>
    </div>
  )
}
`
}

function generateParquetRouteEdit(params: RouteEditParams): string {
  const { name, pluralName, typeName, formName, paramName, apiPath } = params

  return `// 🔄 GENERATED by codegen - parquet/DuckDB data source
// Mutations go to REST API, parquet is read-only

import { createFileRoute, useNavigate } from '@tanstack/react-router'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { type ${typeName} } from '@/collections'
import { ${formName} } from '@/components/forms/${name}-form'
import { PageHeader } from '@/components/shared/page-header'
import { apiClient } from '@/api/client'
import { clearParquetCache } from '@/lib/duckdb-client'
import { toast } from 'sonner'

export const Route = createFileRoute('/_app/${pluralName}/$${paramName}')({
  component: ${typeName}EditPage,
})

function ${typeName}EditPage() {
  const navigate = useNavigate()
  const queryClient = useQueryClient()
  const { ${paramName} } = Route.useParams()

  // Load the item from REST API
  const { data: item, isLoading } = useQuery({
    queryKey: ['${name}', ${paramName}],
    queryFn: async () => {
      const response = await apiClient.get<{ data: ${typeName} }>(\`${apiPath}/\${${paramName}}\`)
      return response.data.data
    },
  })

  const handleSubmit = async (formData: Partial<${typeName}>) => {
    try {
      await apiClient.patch(\`${apiPath}/\${${paramName}}\`, formData)
      // Invalidate caches
      clearParquetCache()
      queryClient.invalidateQueries({ queryKey: ['${pluralName}'] })
      queryClient.invalidateQueries({ queryKey: ['${name}', ${paramName}] })
      toast.success('${typeName} updated successfully')
      navigate({ to: '/${pluralName}' })
    } catch (error) {
      toast.error('Failed to update ${name}')
      console.error(error)
    }
  }

  const handleDelete = async () => {
    if (!confirm('Are you sure you want to delete this ${name}?')) return

    try {
      await apiClient.delete(\`${apiPath}/\${${paramName}}\`)
      clearParquetCache()
      queryClient.invalidateQueries({ queryKey: ['${pluralName}'] })
      toast.success('${typeName} deleted')
      navigate({ to: '/${pluralName}' })
    } catch (error) {
      toast.error('Failed to delete ${name}')
      console.error(error)
    }
  }

  if (isLoading || !item) {
    return (
      <div className="flex items-center justify-center p-8">
        <p className="text-muted-foreground">Loading...</p>
      </div>
    )
  }

  return (
    <div className="flex flex-col gap-6">
      <PageHeader
        title="Edit ${typeName}"
        description="Update ${name} details"
        backLink="/${pluralName}"
      />

      <div className="max-w-2xl">
        <${formName}
          defaultValues={item}
          onSubmit={handleSubmit}
          onDelete={handleDelete}
        />
      </div>
    </div>
  )
}
`
}
