import type { ParsedResource } from '../utils/schema-parser'

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

export function generateRouteNew(resource: ParsedResource): string {
  const { config } = resource
  const { name, pluralName, dataSource } = config
  const typeName = capitalize(name)
  const formName = `${typeName}Form`
  const apiPath = config.apiBasePath ?? `/${pluralName}`

  // Generate parquet-backed route (mutations via REST API)
  if (dataSource === 'parquet') {
    return generateParquetRouteNew({ name, pluralName, typeName, formName, apiPath })
  }

  // Default: JSON/TanStack DB route
  return generateJsonRouteNew({ name, pluralName, typeName, formName })
}

type RouteNewParams = {
  name: string
  pluralName: string
  typeName: string
  formName: string
  apiPath?: string
}

function generateJsonRouteNew(params: RouteNewParams): string {
  const { name, pluralName, typeName, formName } = params

  return `// 🔄 GENERATED by codegen

import { createFileRoute, useNavigate } from '@tanstack/react-router'
import { ${pluralName}Collection, type ${typeName} } from '@/collections'
import { ${formName} } from '@/components/forms/${name}-form'
import { PageHeader } from '@/components/shared/page-header'
import { toast } from 'sonner'

export const Route = createFileRoute('/_app/${pluralName}/new')({
  component: ${typeName}NewPage,
})

function ${typeName}NewPage() {
  const navigate = useNavigate()

  const handleSubmit = async (data: Omit<${typeName}, 'id' | 'created_at' | 'updated_at'>) => {
    try {
      ${pluralName}Collection.insert({
        ...data,
        id: crypto.randomUUID(),
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      } as ${typeName})
      toast.success('${typeName} created successfully')
      navigate({ to: '/${pluralName}' })
    } catch (error) {
      toast.error('Failed to create ${name}')
      console.error(error)
    }
  }

  return (
    <div className="flex flex-col gap-6">
      <PageHeader
        title="New ${typeName}"
        description="Create a new ${name}"
        backLink="/${pluralName}"
      />

      <div className="max-w-2xl">
        <${formName} onSubmit={handleSubmit} />
      </div>
    </div>
  )
}
`
}

function generateParquetRouteNew(params: RouteNewParams): string {
  const { name, pluralName, typeName, formName, apiPath } = params

  return `// 🔄 GENERATED by codegen - parquet/DuckDB data source
// Mutations go to REST API, parquet is read-only

import { createFileRoute, useNavigate } from '@tanstack/react-router'
import { useQueryClient } from '@tanstack/react-query'
import { type ${typeName} } from '@/collections'
import { ${formName} } from '@/components/forms/${name}-form'
import { PageHeader } from '@/components/shared/page-header'
import { apiClient } from '@/api/client'
import { clearParquetCache } from '@/lib/duckdb-client'
import { toast } from 'sonner'

export const Route = createFileRoute('/_app/${pluralName}/new')({
  component: ${typeName}NewPage,
})

function ${typeName}NewPage() {
  const navigate = useNavigate()
  const queryClient = useQueryClient()

  const handleSubmit = async (data: Omit<${typeName}, 'id' | 'created_at' | 'updated_at'>) => {
    try {
      await apiClient.post('${apiPath}', data)
      // Invalidate parquet cache so next query fetches fresh data
      clearParquetCache()
      queryClient.invalidateQueries({ queryKey: ['${pluralName}'] })
      toast.success('${typeName} created successfully')
      navigate({ to: '/${pluralName}' })
    } catch (error) {
      toast.error('Failed to create ${name}')
      console.error(error)
    }
  }

  return (
    <div className="flex flex-col gap-6">
      <PageHeader
        title="New ${typeName}"
        description="Create a new ${name}"
        backLink="/${pluralName}"
      />

      <div className="max-w-2xl">
        <${formName} onSubmit={handleSubmit} />
      </div>
    </div>
  )
}
`
}
