import type { ParsedResource } from '../utils/schema-parser'

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

export function generateRouteIndex(resource: ParsedResource): string {
  const { config } = resource
  const { name, pluralName, table, search } = config
  const typeName = capitalize(name)
  const displayName = capitalize(pluralName)

  // Get columns from config or default to all non-hidden fields
  const columns = table?.columns ?? ['id']
  const searchableFields = table?.searchableFields ?? search?.searchableFields ?? []
  const filterableFields = table?.filterableFields ?? []
  const defaultSort = table?.defaultSort ?? { field: 'created_at', order: 'desc' }

  return `// 🔄 GENERATED by codegen

import { createFileRoute, Link } from '@tanstack/react-router'
import { z } from 'zod'
import { useLiveQuery } from '@tanstack/react-db'
import { ${pluralName}Collection } from '@/collections'
import { ${name}Columns } from '@/components/tables/${name}-columns'
import { DataTable } from '@/components/shared/data-table'
import { PageHeader } from '@/components/shared/page-header'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Plus, Search } from 'lucide-react'

const searchParamsSchema = z.object({
  page: z.number().default(1),
  pageSize: z.number().default(20),
  search: z.string().optional(),
  sort: z.string().default('${defaultSort.field}'),
  order: z.enum(['asc', 'desc']).default('${defaultSort.order}'),
})

export const Route = createFileRoute('/_app/${pluralName}/')({
  validateSearch: searchParamsSchema,
  component: ${displayName}IndexPage,
})

function ${displayName}IndexPage() {
  const navigate = Route.useNavigate()
  const { page, pageSize, search, sort, order } = Route.useSearch()

  // Live query from TanStack DB
  const { data: items = [], isLoading } = useLiveQuery((q) => {
    let query = q.from({ item: ${pluralName}Collection })

    // Apply search filter
    ${searchableFields.length > 0 ? `if (search) {
      query = query.where(({ item }) =>
        item.${searchableFields[0]}.toLowerCase().includes(search.toLowerCase())
      )
    }` : '// No searchable fields configured'}

    // Apply sorting
    query = query.orderBy(({ item }) => item[sort as keyof typeof item], order)

    return query
  })

  // Client-side pagination
  const totalCount = items.length
  const paginatedData = items.slice((page - 1) * pageSize, page * pageSize)

  return (
    <div className="flex flex-col gap-4">
      <PageHeader
        title="${displayName}"
        description="${config.description ?? `Manage your ${pluralName}`}"
        action={
          <Button asChild>
            <Link to="/${pluralName}/new">
              <Plus className="mr-2 h-4 w-4" />
              New ${typeName}
            </Link>
          </Button>
        }
      />

      <div className="flex items-center gap-4">
        <div className="relative flex-1 max-w-sm">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input
            placeholder="Search ${pluralName}..."
            value={search ?? ''}
            onChange={(e) =>
              navigate({
                search: (prev) => ({
                  ...prev,
                  search: e.target.value || undefined,
                  page: 1,
                }),
              })
            }
            className="pl-9"
          />
        </div>
      </div>

      <DataTable
        columns={${name}Columns}
        data={paginatedData}
        isLoading={isLoading}
      />

      {/* Pagination */}
      <div className="flex items-center justify-between">
        <p className="text-sm text-muted-foreground">
          Showing {paginatedData.length} of {totalCount} results
        </p>
        <div className="flex gap-2">
          <Button
            variant="outline"
            size="sm"
            disabled={page === 1}
            onClick={() =>
              navigate({ search: (prev) => ({ ...prev, page: page - 1 }) })
            }
          >
            Previous
          </Button>
          <Button
            variant="outline"
            size="sm"
            disabled={page * pageSize >= totalCount}
            onClick={() =>
              navigate({ search: (prev) => ({ ...prev, page: page + 1 }) })
            }
          >
            Next
          </Button>
        </div>
      </div>
    </div>
  )
}
`
}
