import type { ParsedResource } from '../utils/schema-parser'

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

export function generateRouteIndex(resource: ParsedResource): string {
  const { config } = resource
  const { name, pluralName, table, search, dataSource } = config
  const typeName = capitalize(name)
  const displayName = capitalize(pluralName)

  // Get columns from config or default to all non-hidden fields
  const searchableFields = table?.searchableFields ?? search?.searchableFields ?? []
  const defaultSort = table?.defaultSort ?? { field: 'created_at', order: 'desc' }

  // Generate parquet-backed route
  if (dataSource === 'parquet') {
    return generateParquetRouteIndex({
      name,
      pluralName,
      typeName,
      displayName,
      searchableFields,
      defaultSort,
      description: config.description,
      analyticsEnabled: config.analytics?.enabled ?? false,
    })
  }

  // Default: JSON/TanStack DB route
  return generateJsonRouteIndex({
    name,
    pluralName,
    typeName,
    displayName,
    searchableFields,
    defaultSort,
    description: config.description,
  })
}

type RouteIndexParams = {
  name: string
  pluralName: string
  typeName: string
  displayName: string
  searchableFields: string[]
  defaultSort: { field: string; order: string }
  description?: string
  analyticsEnabled?: boolean
}

/**
 * Generate route for JSON/TanStack DB data source (existing behavior)
 */
function generateJsonRouteIndex(params: RouteIndexParams): string {
  const { name, pluralName, typeName, displayName, searchableFields, defaultSort, description } = params

  return `// 🔄 GENERATED by codegen

import { createFileRoute, Link, useNavigate } from '@tanstack/react-router'
import { z } from 'zod'
import { useLiveQuery } from '@tanstack/react-db'
import { IconPlus, IconSearch } from '@tabler/icons-react'
import { ${pluralName}Collection } from '@/collections'
import { ${name}Columns } from '@/components/tables/${name}-columns'
import { DataTableEnhanced } from '@/components/shared/data-table-enhanced'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'

const searchParamsSchema = z.object({
  search: z.string().optional(),
  sort: z.string().default('${defaultSort.field}'),
  order: z.enum(['asc', 'desc']).default('${defaultSort.order}'),
})

export const Route = createFileRoute('/_app/${pluralName}/')({
  validateSearch: searchParamsSchema,
  component: ${displayName}IndexPage,
})

function ${displayName}IndexPage() {
  const routeNavigate = Route.useNavigate()
  const globalNavigate = useNavigate()
  const { search, sort, order } = Route.useSearch()

  // Live query from TanStack DB
  const { data: items = [], isLoading } = useLiveQuery((q) => {
    let query = q.from({ item: ${pluralName}Collection })

    // Apply search filter
    ${searchableFields.length > 0 ? `if (search) {
      query = query.where(({ item }) =>
        item.${searchableFields[0]}.toLowerCase().includes(search.toLowerCase())
      )
    }` : '// No searchable fields configured'}

    // Apply sorting
    query = query.orderBy(({ item }) => item[sort as keyof typeof item], order)

    return query
  })

  const handleRowClick = (row: (typeof items)[0]) => {
    globalNavigate({ to: '/${pluralName}/$id/edit', params: { id: row.id } })
  }

  return (
    <div className="flex flex-col gap-6">
      {/* Header */}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">${displayName}</h1>
          <p className="text-muted-foreground text-sm">${description ?? `Manage your ${pluralName}`}</p>
        </div>
        <Button asChild>
          <Link to="/${pluralName}/new">
            <IconPlus className="mr-2 h-4 w-4" />
            New ${typeName}
          </Link>
        </Button>
      </div>

      {/* Search */}
      <div className="flex items-center gap-4">
        <div className="relative flex-1 max-w-sm">
          <IconSearch className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input
            placeholder="Search ${pluralName}..."
            value={search ?? ''}
            onChange={(e) =>
              routeNavigate({
                search: (prev) => ({
                  ...prev,
                  search: e.target.value || undefined,
                }),
              })
            }
            className="pl-9"
          />
        </div>
      </div>

      {/* Table */}
      <DataTableEnhanced
        columns={${name}Columns}
        data={items}
        isLoading={isLoading}
        onRowClick={handleRowClick}
      />
    </div>
  )
}
`
}

/**
 * Generate route for parquet/DuckDB data source (windowed loading)
 */
function generateParquetRouteIndex(params: RouteIndexParams): string {
  const { name, pluralName, typeName, displayName, searchableFields, defaultSort, description, analyticsEnabled } = params

  // Build search field conditions for SQL WHERE clause
  const searchConditions = searchableFields.length > 0
    ? searchableFields.map(f => `LOWER(COALESCE(${f}, '')) LIKE LOWER('%' || \${escaped} || '%')`).join(' OR ')
    : `LOWER(COALESCE(id, '')) LIKE LOWER('%' || \${escaped} || '%')`

  const iconImports = analyticsEnabled ? 'IconPlus, IconSearch, IconChartBar' : 'IconPlus, IconSearch'

  return `// 🔄 GENERATED by codegen - parquet/DuckDB data source

import { useState, useEffect, useCallback } from 'react'
import { createFileRoute, Link, useNavigate } from '@tanstack/react-router'
import { z } from 'zod'
import { ${iconImports} } from '@tabler/icons-react'
import { use${typeName}WindowedQuery, build${typeName}Where, type ${typeName} } from '@/collections/${pluralName}.collection'
import { ${name}Columns } from '@/components/tables/${name}-columns'
import { DataTableVirtualDynamic } from '@/components/shared/data-table-virtual-dynamic'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'

const searchParamsSchema = z.object({
  search: z.string().optional(),
  sort: z.string().default('${defaultSort.field}'),
  order: z.enum(['asc', 'desc']).default('${defaultSort.order}'),
})

export const Route = createFileRoute('/_app/${pluralName}/')({
  validateSearch: searchParamsSchema,
  component: ${displayName}IndexPage,
})

function ${displayName}IndexPage() {
  const routeNavigate = Route.useNavigate()
  const globalNavigate = useNavigate()
  const { search, sort, order } = Route.useSearch()
  const [totalCount, setTotalCount] = useState(0)
  const [isLoadingCount, setIsLoadingCount] = useState(true)

  // Build WHERE clause from search params
  const whereClause = build${typeName}Where({ search })
  const orderByClause = \`\${sort} \${order.toUpperCase()}\`

  // Windowed query hook for on-demand row fetching
  const { fetchRows, getTotalCount } = use${typeName}WindowedQuery({
    where: whereClause,
    orderBy: orderByClause,
  })

  // Fetch total count when filters change
  useEffect(() => {
    setIsLoadingCount(true)
    getTotalCount()
      .then(setTotalCount)
      .finally(() => setIsLoadingCount(false))
  }, [getTotalCount, whereClause])

  const handleRowClick = useCallback((row: ${typeName}) => {
    globalNavigate({ to: '/${pluralName}/$id/edit', params: { id: row.id } })
  }, [globalNavigate])

  return (
    <div className="flex flex-col gap-6">
      {/* Header */}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">${displayName}</h1>
          <p className="text-muted-foreground text-sm">${description ?? `Manage your ${pluralName}`}</p>
        </div>
        <div className="flex gap-2">
          ${analyticsEnabled ? `<Button variant="outline" asChild>
            <Link to="/${pluralName}/analytics">
              <IconChartBar className="mr-2 h-4 w-4" />
              Analytics
            </Link>
          </Button>` : ''}
          <Button asChild>
            <Link to="/${pluralName}/new">
              <IconPlus className="mr-2 h-4 w-4" />
              New ${typeName}
            </Link>
          </Button>
        </div>
      </div>

      {/* Search */}
      <div className="flex items-center gap-4">
        <div className="relative flex-1 max-w-sm">
          <IconSearch className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input
            placeholder="Search ${pluralName}..."
            value={search ?? ''}
            onChange={(e) =>
              routeNavigate({
                search: (prev) => ({
                  ...prev,
                  search: e.target.value || undefined,
                }),
              })
            }
            className="pl-9"
          />
        </div>
      </div>

      {/* Table */}
      <DataTableVirtualDynamic
        columns={${name}Columns}
        totalCount={totalCount}
        fetchRows={fetchRows}
        isLoading={isLoadingCount}
        onRowClick={handleRowClick}
        maxHeight="calc(100vh - 280px)"
      />
    </div>
  )
}
`
}
