import type { ParsedResource } from '../utils/schema-parser'

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

export function generateRouteEdit(resource: ParsedResource): string {
  const { config } = resource
  const { name, pluralName } = config
  const typeName = capitalize(name)
  const formName = `${typeName}Form`
  const paramName = `${name}Id`

  return `// 🔄 GENERATED by codegen

import { createFileRoute, useNavigate } from '@tanstack/react-router'
import { useLiveQuery, useCollection } from '@tanstack/react-db'
import { ${pluralName}Collection } from '@/collections'
import { ${formName} } from '@/components/forms/${name}-form'
import { PageHeader } from '@/components/shared/page-header'
import { toast } from 'sonner'

export const Route = createFileRoute('/_app/${pluralName}/$${paramName}')({
  component: ${typeName}EditPage,
})

function ${typeName}EditPage() {
  const navigate = useNavigate()
  const { ${paramName} } = Route.useParams()
  const collection = useCollection(${pluralName}Collection)

  // Load the item
  const { data } = useLiveQuery((q) =>
    q
      .from({ item: ${pluralName}Collection })
      .where(({ item }) => item.id === ${paramName})
  )

  const item = data?.[0]

  const handleSubmit = async (formData: Parameters<typeof collection.update>[0]) => {
    try {
      await collection.update({
        ...formData,
        id: ${paramName},
        updated_at: new Date().toISOString(),
      })
      toast.success('${typeName} updated successfully')
      navigate({ to: '/${pluralName}' })
    } catch (error) {
      toast.error('Failed to update ${name}')
      console.error(error)
    }
  }

  const handleDelete = async () => {
    if (!confirm('Are you sure you want to delete this ${name}?')) return

    try {
      await collection.delete(${paramName})
      toast.success('${typeName} deleted')
      navigate({ to: '/${pluralName}' })
    } catch (error) {
      toast.error('Failed to delete ${name}')
      console.error(error)
    }
  }

  if (!item) {
    return (
      <div className="flex items-center justify-center p-8">
        <p className="text-muted-foreground">Loading...</p>
      </div>
    )
  }

  return (
    <div className="flex flex-col gap-6">
      <PageHeader
        title="Edit ${typeName}"
        description="Update ${name} details"
        backLink="/${pluralName}"
      />

      <div className="max-w-2xl">
        <${formName}
          defaultValues={item}
          onSubmit={handleSubmit}
          onDelete={handleDelete}
        />
      </div>
    </div>
  )
}
`
}
