import { createFileRoute, Link } from '@tanstack/react-router'
import { IconForms, IconTable, IconChartBar, IconPalette } from '@tabler/icons-react'

export const Route = createFileRoute('/showcase/')({
  component: ShowcaseOverview,
})

const sections = [
  {
    title: 'Tables',
    description: 'Data tables with pagination, column visibility, sorting - as generated by codegen',
    href: '/showcase/tables',
    icon: IconTable,
  },
  {
    title: 'Forms',
    description: 'Form layouts with inputs, selects, validation states - as generated by codegen',
    href: '/showcase/forms',
    icon: IconForms,
  },
  {
    title: 'Charts',
    description: 'Interactive area/bar/line/pie charts with time range controls - as generated by codegen',
    href: '/showcase/charts',
    icon: IconChartBar,
  },
  {
    title: 'Colors',
    description: 'Theme color palette and design tokens',
    href: '/showcase/colors',
    icon: IconPalette,
  },
]

function ShowcaseOverview() {
  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight">Component Showcase</h1>
        <p className="text-muted-foreground text-sm mt-1">
          Visual reference for components generated by codegen. Use this to design and iterate
          on the look and feel without real data.
        </p>
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        {sections.map((section) => (
          <Link
            key={section.href}
            to={section.href}
            className="group block p-6 border rounded-lg hover:border-primary hover:bg-accent/50 transition-colors"
          >
            <div className="flex items-start gap-4">
              <div className="p-2 rounded-md bg-primary/10 text-primary">
                <section.icon className="h-6 w-6" />
              </div>
              <div>
                <h2 className="font-semibold group-hover:text-primary transition-colors">
                  {section.title}
                </h2>
                <p className="text-sm text-muted-foreground mt-1">
                  {section.description}
                </p>
              </div>
            </div>
          </Link>
        ))}
      </div>

      <div className="p-4 border rounded-lg bg-muted/50">
        <h3 className="font-medium">Quick Setup</h3>
        <p className="text-sm text-muted-foreground mt-1">
          If components are missing, run:
        </p>
        <pre className="mt-2 p-2 bg-background rounded text-sm font-mono">
          pnpm setup-ui
        </pre>
      </div>
    </div>
  )
}
